
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INSERT INTO VALUES SET COLUMN_NAME TABLE_NAME LPAREN RPAREN EQUALS STRING_LIT INT_LIT DOUBLE_LIT DATE_LIT COMMAstatement : INSERT INTO TABLE_NAME VALUES LPAREN valuelist RPAREN\n            | INSERT INTO TABLE_NAME SET assignmentlistvaluelist : expr\n            | expr COMMA valuelistassignmentlist : assignment\n            | assignment COMMA assignmentassignment : COLUMN_NAME EQUALS exprexpr : STRING_LIT\n            | INT_LIT\n            | DOUBLE_LIT\n            | DATE_LIT'
    
_lr_action_items = {'INSERT':([0,],[2,]),'$end':([1,8,9,13,14,15,16,19,21,22,],[0,-2,-5,-8,-9,-10,-11,-1,-6,-7,]),'INTO':([2,],[3,]),'TABLE_NAME':([3,],[4,]),'VALUES':([4,],[5,]),'SET':([4,],[6,]),'LPAREN':([5,],[7,]),'COLUMN_NAME':([6,17,],[10,10,]),'STRING_LIT':([7,18,20,],[13,13,13,]),'INT_LIT':([7,18,20,],[14,14,14,]),'DOUBLE_LIT':([7,18,20,],[15,15,15,]),'DATE_LIT':([7,18,20,],[16,16,16,]),'COMMA':([9,12,13,14,15,16,22,],[17,20,-8,-9,-10,-11,-7,]),'EQUALS':([10,],[18,]),'RPAREN':([11,12,13,14,15,16,23,],[19,-3,-8,-9,-10,-11,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'assignmentlist':([6,],[8,]),'assignment':([6,17,],[9,21,]),'valuelist':([7,20,],[11,23,]),'expr':([7,18,20,],[12,22,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> INSERT INTO TABLE_NAME VALUES LPAREN valuelist RPAREN','statement',7,'p_statement_query','insert.py',63),
  ('statement -> INSERT INTO TABLE_NAME SET assignmentlist','statement',5,'p_statement_query','insert.py',64),
  ('valuelist -> expr','valuelist',1,'p_value_list','insert.py',67),
  ('valuelist -> expr COMMA valuelist','valuelist',3,'p_value_list','insert.py',68),
  ('assignmentlist -> assignment','assignmentlist',1,'p_assignment_list','insert.py',71),
  ('assignmentlist -> assignment COMMA assignment','assignmentlist',3,'p_assignment_list','insert.py',72),
  ('assignment -> COLUMN_NAME EQUALS expr','assignment',3,'p_assignment','insert.py',75),
  ('expr -> STRING_LIT','expr',1,'p_expr','insert.py',78),
  ('expr -> INT_LIT','expr',1,'p_expr','insert.py',79),
  ('expr -> DOUBLE_LIT','expr',1,'p_expr','insert.py',80),
  ('expr -> DATE_LIT','expr',1,'p_expr','insert.py',81),
]
