
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INSERT INTO VALUES COLUMN_NAME TABLE_NAME LPAREN RPAREN NAME EQUALSstatement : INSERT INTO TABLE_NAME\n    insertoption : valuelist\n                |   assignmentlist\n    valuelist : VALUES LPAREN NAME RPARENassignmentlist : NAME'
    
_lr_action_items = {'INSERT':([0,],[2,]),'$end':([1,4,],[0,-1,]),'INTO':([2,],[3,]),'TABLE_NAME':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> INSERT INTO TABLE_NAME','statement',3,'p_statement_query','insert.py',81),
  ('insertoption -> valuelist','insertoption',1,'p_insert_option','insert.py',85),
  ('insertoption -> assignmentlist','insertoption',1,'p_insert_option','insert.py',86),
  ('valuelist -> VALUES LPAREN NAME RPAREN','valuelist',4,'p_value_list','insert.py',90),
  ('assignmentlist -> NAME','assignmentlist',1,'p_assignment_list','insert.py',93),
]
